### ISSUE TITLE
capsolver.error.InvalidRequestError: InvalidRequestError: clientKey error

### ISSUE THREAD

**Issue by Aunero** [turfintl/arkose-capsolver#1]
Exception happened during processing of request from ('127.0.0.1', 61654)
Traceback (most recent call last):
  File "/usr/lib64/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib64/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "main.py", line 38, in do_GET
    token = get_token()
  File "main.py", line 17, in get_token
    "websiteURL": "https://chat.openai.com",
  File "/usr/local/lib/python3.6/site-packages/capsolver/capsolver.py", line 39, in solve
    raise r
capsolver.error.InvalidRequestError: InvalidRequestError: clientKey error
----------------------------

已经在capsolver注册并充值，token已经写入main.py，但是报错

**Comment by turfintl** [comment]
上传代码时删自己key，不小心把赋值的那一行也删了，没发现，已更新代码。
